[project]
name = "lit-auto-encoder"
version = "0.1.0"
description = "A simple autoencoder based on PyTorch Lightning."
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "David Tiefenthaler"}
]
requires-python = ">=3.12.0, <3.13.0"
dependencies = [
    "lightning>=2.4.0",
    "torch>=2.4.1",
    "torchvision>=0.20.1",
]

# [tool.hatch.build.targets.wheel]
# packages = ["src/lit_auto_encoder"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
